name: Rescan Application in CAST AIP

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Manual trigger from Actions tab

jobs:
  robocopy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create log directory
        run: mkdir C:\robocopy_logs

      - name: Run robocopy
        run: robocopy D:\a\Shopizer\Shopizer C:\Users\JKM\Documents\Cast_Software\G\SOURCES\Shopizer /E /IS /LOG:C:\robocopy_logs\robocopy_log.txt /NP /NFL /NDL /TEE
      
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify the Java version
          distribution: 'adopt'  # Specify the distribution (e.g., adopt, openjdk)
      
      - name: Rescan Application
        env:
          AIP_CONSOLE_USERNAME: admin
          AIP_CONSOLE_PASSWORD: admin
        run: |
          cd C:\Users\JKM\Documents\Cast_Software\G\SOURCES\Shopizer
          java -jar JAR/aip-console-tools-cli.jar add --apikey="8uENrFd8.p7IwCkQbaGoMRR79s5TTSyxTGnskl9N8" --n SHOPIZER --console-url http://localhost:8081 -f C:\Users\JKM\Documents\Cast_Software\G\SOURCES\Shopizer --username ${{ env.AIP_CONSOLE_USERNAME }} --password ${{ env.AIP_CONSOLE_PASSWORD }}
