name: Rescan Application in CAST AIP

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Manual trigger from Actions tab

jobs:
  rescan:
    runs-on: windows-latest
    env:
      LOCAL_REPO_PATH: C:\Users\JKM\Documents\Cast_Software\G\SOURCES\Shopizer  # Define a variable for the local repository path
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy repository to target directory
        run: |
          robocopy ${{ github.workspace }} ${{ env.LOCAL_REPO_PATH }} /E /IS /LOG:C:\robocopy_logs\robocopy_log.txt
      
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify the Java version
          distribution: 'adopt'  # Specify the distribution (e.g., adopt, openjdk)
      
      - name: Rescan Application
        env:
          AIP_CONSOLE_USERNAME: ${{ secrets.AIP_CONSOLE_USERNAME }}
          AIP_CONSOLE_PASSWORD: ${{ secrets.AIP_CONSOLE_PASSWORD }}
        run: |
          cd ${{ env.LOCAL_REPO_PATH }}
          java -jar JAR/aip-console-tools-cli.jar rescan --application SHOPIZER --console-url http://localhost:8081 --username ${{ env.AIP_CONSOLE_USERNAME }} --password ${{ env.AIP_CONSOLE_PASSWORD }}
