name: Rescan Application in CAST AIP

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Manual trigger from Actions tab

jobs:
  rescan:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: List directory contents
        shell: powershell
        run: Get-ChildItem -Path JAR
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Verify network connectivity
        run: |
          ping https://31b8-115-99-190-68.ngrok-free.app  # Ping the server to check connectivity
          curl --head --fail --silent --show-error https://31b8-115-99-190-68.ngrok-free.app  # Check HTTP connectivity

      - name: Rescan Application
        run: |
          java -jar aip-console-tools-cli.jar add --apikey="8uENrFd8.p7IwCkQbaGoMRR79s5TTSyxTGnskl9N8" -n "SHOPIZER" --no-clone --server-url="https://31b8-115-99-190-68.ngrok-free.app" -f "C:\Users\JKM\Documents\Cast_Software\G\SOURCES\Shopizer" --verbose=false --set-as-current=true
