name: Rescan Application in CAST AIP

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Manual trigger from Actions tab

jobs:
  rescan:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Copy repository to target directory
        run: |
          robocopy D:\a\Shopizer\Shopizer C:\Users\JKM\Documents\Cast_Software\G\SOURCES\Shopizer /E /IS

      
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify the Java version
          distribution: 'adopt'  # Specify the distribution (e.g., adopt, openjdk)
      
      - name: Rescan Application
        env:
          AIP_CONSOLE_USERNAME: admin
          AIP_CONSOLE_PASSWORD: admin
        run: |
          cd C:/Users/JKM/Documents/Cast_Software/G/SOURCES/Shopizer
          java -jar JAR/aip-console-tools-cli.jar add --application SHOPIZER --apikey="8uENrFd8.p7IwCkQbaGoMRR79s5TTSyxTGnskl9N8" --console-url http://localhost:8081 -f C:/Users/JKM/Documents/Cast_Software/G/SOURCES/Shopizer.zip --username ${{ env.admin }} --password ${{ env.admin }}
