name: Rescan Application in CAST AIP

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Manual trigger from Actions tab

jobs:
  rescan:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create symbolic link to C:\Shopizer
        run: New-Item -ItemType SymbolicLink -Path 'D:\a\Shopizer\Shopizer' -Name 'Shopizer' -Value 'C:\Shopizer' -Force

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Rescan Application
        env:
          AIP_CONSOLE_USERNAME: admin
          AIP_CONSOLE_PASSWORD: admin
        run: |
          java -jar JAR/aip-console-tools-cli.jar add --apikey="8uENrFd8.p7IwCkQbaGoMRR79s5TTSyxTGnskl9N8" --n SHOPIZER --server-url="http://localhost:8081" -f \\jkmlap1\VMWINShare\SOURCES\Shopizer.zip --verbose=false --set-as-current=true

